title: codeCheets
email: vu.monica.05@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An open source collection of coding cheat cheets
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Monica-Vu

# Build settings
markdown: kramdown

# Syntax Highlighter
highlighter: rouge

# Location of the languages
collections_dir: _collections

permalink: /:categories/:title:output_ext

collections:
  # Each language or page has is treated as a Jekyll Collection https://jekyllrb.com/docs/collections/
  Java:
    output: true
    icon: https://cdn-images-1.medium.com/max/1600/1*E4CO83SmCCrvRrge7U3Ahw.jpeg
  Python3:
    output: true
    icon: https://s3.amazonaws.com/com.twilio.prod.twilio-docs/images/header.width-808.gif
  JavaScript:
    output: true
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/1200px-Unofficial_JavaScript_logo_2.svg.png
  CPP:
    output: true
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1200px-ISO_C%2B%2B_Logo.svg.png
  C:
    icon: https://prod-discovery.edx-cdn.org/media/course/image/bb5e9463-0248-4f78-a337-b8bb9d829f2b-dc9bc100a72f.small.jpg
  # Disable the automatic posts collection in Jekyll
  posts:
    output: false
